(******************************************************************************)
(*                                                                            *)
(*            Space Lower Bounds for Streaming Subgraph Detection             *)
(*                                                                            *)
(*     Single-pass space for subgraph isomorphism in turnstile streams        *)
(*     requires Omega(n^(1-epsilon)). Reduction from INDEX via                *)
(*     communication complexity. Parameterized over pattern graph P.          *)
(*                                                                            *)
(*     "You cannot step into the same river twice."                           *)
(*     – Heraclitus, fr. 91                                                   *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: March 20, 2026                                                   *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
